apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-backend
  template:
    metadata:
      labels:
        app: travel-backend
    spec:
      containers:
        - name: travel-backend
          image: travel-backend:1.0
          ports:
            - containerPort: 8080
