apiVersion: v1
kind: Service
metadata:
  name: travel-frontend-service
spec:
  selector:
    app: travel-frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: NodePort
